// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actionmap.h"


/////////////////////////////////////////////////////////////////////////////
// CActionMap properties

long CActionMap::GetAction()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CActionMap::SetAction(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

short CActionMap::GetMessage()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

short CActionMap::GetModifier()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

short CActionMap::GetKeycode()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

LPDISPATCH CActionMap::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x5, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CActionMap operations
