#if !defined(AFX_AXISSTYLE_H__12DF2558_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_AXISSTYLE_H__12DF2558_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLineStyle;

/////////////////////////////////////////////////////////////////////////////
// CAxisStyle wrapper class

class CAxisStyle : public COleDispatchDriver
{
public:
	CAxisStyle() {}		// Calls COleDispatchDriver default constructor
	CAxisStyle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisStyle(const CAxisStyle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetTickLength();
	void SetTickLength(short);
	CLineStyle GetLineStyle();
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISSTYLE_H__12DF2558_6AF6_11D4_AC53_444553546170__INCLUDED_)
