// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "axisstyle.h"

// Dispatch interfaces referenced by this interface
#include "linestyle.h"


/////////////////////////////////////////////////////////////////////////////
// CAxisStyle properties

short CAxisStyle::GetTickLength()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CAxisStyle::SetTickLength(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

CLineStyle CAxisStyle::GetLineStyle()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CLineStyle(pDispatch);
}

LPDISPATCH CAxisStyle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CAxisStyle operations
