#if !defined(AFX_AXIS_H__12DF252B_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_AXIS_H__12DF252B_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLabel;
class CDerivedDouble;
class CDerivedLong;
class CValueLabelCollection;
class CTimeScale;
class CGridLines;
class COleFont;
class CValueFormat;
class CAxisStyle;

/////////////////////////////////////////////////////////////////////////////
// CAxis wrapper class

class CAxis : public COleDispatchDriver
{
public:
	CAxis() {}		// Calls COleDispatchDriver default constructor
	CAxis(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxis(const CAxis& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CLabel GetTitle();
	CDerivedDouble GetOrigin();
	CDerivedDouble GetDataMin();
	CDerivedDouble GetDataMax();
	CDerivedDouble GetMin();
	CDerivedDouble GetMax();
	CDerivedDouble GetNumSpacing();
	CDerivedDouble GetTickSpacing();
	CDerivedLong GetPrecision();
	CValueLabelCollection GetValueLabels();
	CTimeScale GetTimeScale();
	CGridLines GetMajorGrid();
	CString GetName();
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	BOOL GetIsLogarithmic();
	void SetIsLogarithmic(BOOL);
	BOOL GetIsReversed();
	void SetIsReversed(BOOL);
	long GetTitleRotation();
	void SetTitleRotation(long);
	long GetAnnotationRotation();
	void SetAnnotationRotation(long);
	long GetAnnotationMethod();
	void SetAnnotationMethod(long);
	long GetAnnotationPlacement();
	void SetAnnotationPlacement(long);
	long GetOriginPlacement();
	void SetOriginPlacement(long);
	long GetNumMethod();
	void SetNumMethod(long);
	double GetConstant();
	void SetConstant(double);
	double GetMultiplier();
	void SetMultiplier(double);
	LPDISPATCH GetParent();
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	double GetOriginBase();
	void SetOriginBase(double);
	CDerivedDouble GetAnnotationAngle();
	CValueFormat GetLabelFormat();
	void SetLabelFormat(LPDISPATCH);
	BOOL GetIs100Percent();
	void SetIs100Percent(BOOL);
	double GetAnnotationRotationAngle();
	void SetAnnotationRotationAngle(double);
	CAxisStyle GetAxisStyle();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXIS_H__12DF252B_6AF6_11D4_AC53_444553546170__INCLUDED_)
