#if !defined(AFX_BORDER_H__12DF2553_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_BORDER_H__12DF2553_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBorder wrapper class

class CBorder : public COleDispatchDriver
{
public:
	CBorder() {}		// Calls COleDispatchDriver default constructor
	CBorder(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBorder(const CBorder& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetWidth();
	void SetWidth(long);
	long GetType();
	void SetType(long);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BORDER_H__12DF2553_6AF6_11D4_AC53_444553546170__INCLUDED_)
