// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "candle.h"


/////////////////////////////////////////////////////////////////////////////
// CCandle properties

BOOL CCandle::GetIsComplex()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCandle::SetIsComplex(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

LPDISPATCH CCandle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x2, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CCandle operations
