#if !defined(AFX_CHART2DDATAINDEXRESULT_H__12DF2532_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_CHART2DDATAINDEXRESULT_H__12DF2532_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChart2DDataIndexResult wrapper class

class CChart2DDataIndexResult : public COleDispatchDriver
{
public:
	CChart2DDataIndexResult() {}		// Calls COleDispatchDriver default constructor
	CChart2DDataIndexResult(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart2DDataIndexResult(const CChart2DDataIndexResult& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetRegion();
	void SetRegion(long);
	long GetSeries();
	void SetSeries(long);
	long GetPoint();
	void SetPoint(long);
	long GetDistance();
	void SetDistance(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART2DDATAINDEXRESULT_H__12DF2532_6AF6_11D4_AC53_444553546170__INCLUDED_)
