// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chartstyle.h"

// Dispatch interfaces referenced by this interface
#include "LineStyle.h"
#include "FillStyle.h"
#include "SymbolStyle.h"
#include "SliceStyle.h"


/////////////////////////////////////////////////////////////////////////////
// CChartStyle properties

CLineStyle CChartStyle::GetLine()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return CLineStyle(pDispatch);
}

CFillStyle CChartStyle::GetFill()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CFillStyle(pDispatch);
}

CSymbolStyle CChartStyle::GetSymbol()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CSymbolStyle(pDispatch);
}

LPDISPATCH CChartStyle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

CSliceStyle CChartStyle::GetSlice()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CSliceStyle(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CChartStyle operations
