// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chart2dchecknewpointsresult.h"


/////////////////////////////////////////////////////////////////////////////
// CChart2DCheckNewPointsResult properties

BOOL CChart2DCheckNewPointsResult::GetIsInside()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CChart2DCheckNewPointsResult::SetIsInside(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CChart2DCheckNewPointsResult::GetIsOutsideXMin()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CChart2DCheckNewPointsResult::SetIsOutsideXMin(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CChart2DCheckNewPointsResult::GetIsOutsideXMax()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CChart2DCheckNewPointsResult::SetIsOutsideXMax(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CChart2DCheckNewPointsResult::GetIsOutsideYMin()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CChart2DCheckNewPointsResult::SetIsOutsideYMin(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CChart2DCheckNewPointsResult::GetIsOutsideYMax()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CChart2DCheckNewPointsResult::SetIsOutsideYMax(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CChart2DCheckNewPointsResult operations
