#if !defined(AFX_CHART2D_H__12DF2537_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_CHART2D_H__12DF2537_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTitle;
class CLegend;
class CBorder;
class CInterior;
class CChartArea;
class CChartGroupCollection;
class CChartLabelCollection;
class CActionMapCollection;

/////////////////////////////////////////////////////////////////////////////
// CChart2D wrapper class

class CChart2D : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChart2D)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x92d71e93, 0x25a8, 0x11cf, { 0xa6, 0x40, 0x99, 0x86, 0xb6, 0x4d, 0x96, 0x18 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CTitle GetHeader();
	CTitle GetFooter();
	CLegend GetLegend();
	CBorder GetBorder();
	CInterior GetInterior();
	BOOL GetIsBatched();
	void SetIsBatched(BOOL);
	BOOL GetIsDoubleBuffered();
	void SetIsDoubleBuffered(BOOL);
	CChartArea GetChartArea();
	CChartGroupCollection GetChartGroups();
	CChartLabelCollection GetChartLabels();
	long GetErrorOffset();
	void SetErrorOffset(long);
	CActionMapCollection GetActionMaps();
	OLE_HANDLE GetHWnd();
	BOOL GetAllowUserChanges();
	void SetAllowUserChanges(BOOL);
	LPUNKNOWN GetDataSource();
	void SetDataSource(LPUNKNOWN);
	CString GetDataPath();
	void SetDataPath(LPCTSTR);

// Operations
public:
	void Refresh();
	BOOL Load(LPCTSTR FileName);
	BOOL Save(LPCTSTR FileName);
	void CallAction(long Action, long XCoord, long YCoord);
	BOOL DrawToDC(long Hdc, long Format, long Scale, long Left, long Top, long Width, long Height);
	BOOL PrintChart(long Format, long Scale, long Left, long Top, long Width, long Height);
	BOOL CopyToClipboard(long Format);
	BOOL DrawToFile(LPCTSTR FileName, long Format);
	BOOL ShowChartEditorElement(short Element, BOOL Show);
	BOOL IsChartEditorElementVisible(short Element);
	BOOL LoadURL(LPCTSTR URLName);
	BOOL SaveImageAsJpeg(LPCTSTR FileName, long Quality, BOOL GrayScale, BOOL OptimizeCompression, BOOL ProgressiveJpeg);
	BOOL SaveImageAsPng(LPCTSTR FileName, BOOL Interlace);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART2D_H__12DF2537_6AF6_11D4_AC53_444553546170__INCLUDED_)
