// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chart2ddataindexresult.h"


/////////////////////////////////////////////////////////////////////////////
// CChart2DDataIndexResult properties

long CChart2DDataIndexResult::GetRegion()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CChart2DDataIndexResult::SetRegion(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CChart2DDataIndexResult::GetSeries()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CChart2DDataIndexResult::SetSeries(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CChart2DDataIndexResult::GetPoint()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CChart2DDataIndexResult::SetPoint(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CChart2DDataIndexResult::GetDistance()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CChart2DDataIndexResult::SetDistance(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CChart2DDataIndexResult operations
