#if !defined(AFX_CHARTAREA_H__12DF2543_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_CHARTAREA_H__12DF2543_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder;
class CLocation;
class CInterior;
class CPlotArea;
class CBar;
class CPie;
class CMarkerCollection;
class CAxisCollection;
class CView3D;
class CHiLoOpenClose;
class CCandle;
class CPolar;
class CBubble;

/////////////////////////////////////////////////////////////////////////////
// CChartArea wrapper class

class CChartArea : public COleDispatchDriver
{
public:
	CChartArea() {}		// Calls COleDispatchDriver default constructor
	CChartArea(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartArea(const CChartArea& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIsHorizontal();
	void SetIsHorizontal(BOOL);
	CBorder GetBorder();
	CLocation GetLocation();
	CInterior GetInterior();
	CPlotArea GetPlotArea();
	CBar GetBar();
	CPie GetPie();
	CMarkerCollection GetMarkers();
	CAxisCollection GetAxes();
	CView3D GetView3D();
	LPDISPATCH GetParent();
	CHiLoOpenClose GetHiLoOpenClose();
	CCandle GetCandle();
	long GetAngleUnit();
	void SetAngleUnit(long);
	CPolar GetPolar();
	BOOL GetIsShowingOutlines();
	void SetIsShowingOutlines(BOOL);
	CBubble GetBubble();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTAREA_H__12DF2543_6AF6_11D4_AC53_444553546170__INCLUDED_)
