#if !defined(AFX_CHART2DDATA_H__12DF252E_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_CHART2DDATA_H__12DF252E_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChart2DCheckNewPointsResult;

/////////////////////////////////////////////////////////////////////////////
// CChart2DData wrapper class

class CChart2DData : public COleDispatchDriver
{
public:
	CChart2DData() {}		// Calls COleDispatchDriver default constructor
	CChart2DData(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart2DData(const CChart2DData& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetLayout();
	void SetLayout(long);
	long GetNumSeries();
	void SetNumSeries(long);
	long GetFirstSeries();
	void SetFirstSeries(long);
	long GetLastSeries();
	void SetLastSeries(long);
	double GetHoleValue();
	void SetHoleValue(double);
	BOOL GetIsBatched();
	void SetIsBatched(BOOL);
	LPDISPATCH GetParent();
	BOOL GetIsSaved();
	void SetIsSaved(BOOL);
	CString GetFileName();
	void SetFileName(LPCTSTR);
	CString GetDataPath();
	void SetDataPath(LPCTSTR);

// Operations
public:
	long GetNumPoints(long Series);
	void SetNumPoints(long Series, long nNewValue);
	long GetFirstPoint(long Series);
	void SetFirstPoint(long Series, long nNewValue);
	long GetLastPoint(long Series);
	void SetLastPoint(long Series, long nNewValue);
	double GetX(long Series, long Point);
	void SetX(long Series, long Point, double newValue);
	double GetY(long Series, long Point);
	void SetY(long Series, long Point, double newValue);
	BOOL Load(LPCTSTR FileName);
	BOOL ShiftPoints(long Series, long NumPoints, long Dest, long Src);
	BOOL Sort();
	BOOL Save(LPCTSTR FileName);
	BOOL CheckNewPoints(long Series, long NewPoints, BOOL* IsOutsideXMin, BOOL* IsOutsideXMax, BOOL* IsOutsideYMin, BOOL* IsOutsideYMax);
	BOOL DrawNewPoints(long Series, long NewPoints);
	short GetSeriesDisplay(long Series);
	void SetSeriesDisplay(long Series, short nNewValue);
	BOOL CopyXVectorIn(long Series, const VARIANT& vArray);
	BOOL CopyYVectorIn(long Series, const VARIANT& vArray);
	BOOL CopyYArrayIn(const VARIANT& vArray);
	BOOL CopyXVectorOut(long Series, const VARIANT& vArray);
	BOOL CopyYVectorOut(long Series, const VARIANT& vArray);
	BOOL CopyYArrayOut(const VARIANT& vArray);
	long UpdateDataValue(double OldValue, double NewValue);
	CChart2DCheckNewPointsResult CheckNewPointsObject(long Series, long NewPoints);
	BOOL LoadURL(LPCTSTR URLName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART2DDATA_H__12DF252E_6AF6_11D4_AC53_444553546170__INCLUDED_)
