// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chart2dcoordresult.h"


/////////////////////////////////////////////////////////////////////////////
// CChart2DCoordResult properties

long CChart2DCoordResult::GetX()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CChart2DCoordResult::SetX(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CChart2DCoordResult::GetY()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CChart2DCoordResult::SetY(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CChart2DCoordResult operations
