// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dataindex.h"


/////////////////////////////////////////////////////////////////////////////
// CDataIndex properties

long CDataIndex::GetSeries()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CDataIndex::SetSeries(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CDataIndex::GetPoint()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDataIndex::SetPoint(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CDataIndex::GetChartGroup()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CDataIndex::SetChartGroup(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

LPDISPATCH CDataIndex::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CDataIndex operations
