// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datacoord.h"


/////////////////////////////////////////////////////////////////////////////
// CDataCoord properties

double CDataCoord::GetX()
{
	double result;
	GetProperty(0x1, VT_R8, (void*)&result);
	return result;
}

void CDataCoord::SetX(double propVal)
{
	SetProperty(0x1, VT_R8, propVal);
}

double CDataCoord::GetY()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CDataCoord::SetY(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

long CDataCoord::GetChartGroup()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CDataCoord::SetChartGroup(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

LPDISPATCH CDataCoord::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CDataCoord operations
