// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "derivedlong.h"


/////////////////////////////////////////////////////////////////////////////
// CDerivedLong properties

long CDerivedLong::GetValue()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CDerivedLong::SetValue(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CDerivedLong::GetIsDefault()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CDerivedLong::SetIsDefault(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

LPDISPATCH CDerivedLong::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CDerivedLong operations
