// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "derivedenum.h"


/////////////////////////////////////////////////////////////////////////////
// CDerivedEnum properties

short CDerivedEnum::GetValue()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CDerivedEnum::SetValue(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

BOOL CDerivedEnum::GetIsDefault()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CDerivedEnum::SetIsDefault(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

LPDISPATCH CDerivedEnum::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CDerivedEnum operations
