// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "image.h"


/////////////////////////////////////////////////////////////////////////////
// CImage properties

LPDISPATCH CImage::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

CString CImage::GetFileName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CImage::SetFileName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

long CImage::GetLayout()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CImage::SetLayout(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CImage::GetIsEmbedded()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CImage::SetIsEmbedded(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CImage::GetHasMinimumSize()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CImage::SetHasMinimumSize(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CImage operations
