// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "interior.h"

// Dispatch interfaces referenced by this interface
#include "image.h"


/////////////////////////////////////////////////////////////////////////////
// CInterior properties

unsigned long CInterior::GetBackgroundColor()
{
	unsigned long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CInterior::SetBackgroundColor(unsigned long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

unsigned long CInterior::GetForegroundColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CInterior::SetForegroundColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

LPDISPATCH CInterior::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

CImage CInterior::GetImage()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return CImage(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CInterior operations
