// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "legend.h"

// Dispatch interfaces referenced by this interface
#include "border.h"
#include "Location.h"
#include "interior.h"
#include "font.h"
#include "label.h"


/////////////////////////////////////////////////////////////////////////////
// CLegend properties

CBorder CLegend::GetBorder()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return CBorder(pDispatch);
}

CLocation CLegend::GetLocation()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CLocation(pDispatch);
}

CInterior CLegend::GetInterior()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CInterior(pDispatch);
}

BOOL CLegend::GetIsShowing()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CLegend::SetIsShowing(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

long CLegend::GetAnchor()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CLegend::SetAnchor(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CLegend::GetOrientation()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CLegend::SetOrientation(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

LPDISPATCH CLegend::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x7, VT_DISPATCH, (void*)&result);
	return result;
}

COleFont CLegend::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x8, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CLegend::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x8, VT_DISPATCH, propVal);
}

BOOL CLegend::GetIsReversed()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CLegend::SetIsReversed(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

CLabel CLegend::GetText()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return CLabel(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CLegend operations
