#if !defined(AFX_LEGEND_H__12DF255B_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_LEGEND_H__12DF255B_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder;
class CLocation;
class CInterior;
class COleFont;
class CLabel;

/////////////////////////////////////////////////////////////////////////////
// CLegend wrapper class

class CLegend : public COleDispatchDriver
{
public:
	CLegend() {}		// Calls COleDispatchDriver default constructor
	CLegend(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLegend(const CLegend& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CBorder GetBorder();
	CLocation GetLocation();
	CInterior GetInterior();
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	long GetAnchor();
	void SetAnchor(long);
	long GetOrientation();
	void SetOrientation(long);
	LPDISPATCH GetParent();
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetIsReversed();
	void SetIsReversed(BOOL);
	CLabel GetText();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LEGEND_H__12DF255B_6AF6_11D4_AC53_444553546170__INCLUDED_)
