#if !defined(AFX_NUMBERVF_H__12DF2559_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_NUMBERVF_H__12DF2559_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDerivedEnum;
class CDerivedBoolean;

/////////////////////////////////////////////////////////////////////////////
// CNumberVF wrapper class

class CNumberVF : public COleDispatchDriver
{
public:
	CNumberVF() {}		// Calls COleDispatchDriver default constructor
	CNumberVF(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CNumberVF(const CNumberVF& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetDecimalPlaces();
	void SetDecimalPlaces(long);
	BOOL GetUseSeparators();
	void SetUseSeparators(BOOL);
	CDerivedEnum GetOrderSignValue();
	void SetOrderSignValue(LPDISPATCH);
	CDerivedBoolean GetSpaceSeparatingSign();
	void SetSpaceSeparatingSign(LPDISPATCH);
	unsigned long GetNegativeValueColor();
	void SetNegativeValueColor(unsigned long);
	CDerivedBoolean GetUseBrackets();
	void SetUseBrackets(LPDISPATCH);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NUMBERVF_H__12DF2559_6AF6_11D4_AC53_444553546170__INCLUDED_)
