#if !defined(AFX_PLOTAREA_H__12DF2522_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_PLOTAREA_H__12DF2522_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CInterior;
class CDerivedLong;

/////////////////////////////////////////////////////////////////////////////
// CPlotArea wrapper class

class CPlotArea : public COleDispatchDriver
{
public:
	CPlotArea() {}		// Calls COleDispatchDriver default constructor
	CPlotArea(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPlotArea(const CPlotArea& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIsBoxed();
	void SetIsBoxed(BOOL);
	CInterior GetInterior();
	CDerivedLong GetTop();
	CDerivedLong GetBottom();
	CDerivedLong GetLeft();
	CDerivedLong GetRight();
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PLOTAREA_H__12DF2522_6AF6_11D4_AC53_444553546170__INCLUDED_)
