// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "pointstylecollection.h"

// Dispatch interfaces referenced by this interface
#include "chartstyle.h"


/////////////////////////////////////////////////////////////////////////////
// CPointStyleCollection properties

long CPointStyleCollection::GetCount()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

LPDISPATCH CPointStyleCollection::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x2, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CPointStyleCollection operations

CChartStyle CPointStyleCollection::Add(long Series, long Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Series, Point);
	return CChartStyle(pDispatch);
}

void CPointStyleCollection::Remove(long Series, long Point)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Series, Point);
}

CChartStyle CPointStyleCollection::GetItem(long Series, long Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Series, Point);
	return CChartStyle(pDispatch);
}

void CPointStyleCollection::RemoveAll()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CPointStyleCollection::SeriesFromIndex(const VARIANT& Index)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&Index);
	return result;
}

long CPointStyleCollection::PointFromIndex(const VARIANT& Index)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&Index);
	return result;
}

void CPointStyleCollection::Move(long oldSeries, long oldPoint, long newSeries, long newPoint)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 oldSeries, oldPoint, newSeries, newPoint);
}

void CPointStyleCollection::RemoveSeries(long Series)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Series);
}
