#if !defined(AFX_POINTSTYLECOLLECTION_H__12DF2525_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_POINTSTYLECOLLECTION_H__12DF2525_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartStyle;

/////////////////////////////////////////////////////////////////////////////
// CPointStyleCollection wrapper class

class CPointStyleCollection : public COleDispatchDriver
{
public:
	CPointStyleCollection() {}		// Calls COleDispatchDriver default constructor
	CPointStyleCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPointStyleCollection(const CPointStyleCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	LPDISPATCH GetParent();

// Operations
public:
	CChartStyle Add(long Series, long Point);
	void Remove(long Series, long Point);
	CChartStyle GetItem(long Series, long Point);
	void RemoveAll();
	long SeriesFromIndex(const VARIANT& Index);
	long PointFromIndex(const VARIANT& Index);
	void Move(long oldSeries, long oldPoint, long newSeries, long newPoint);
	void RemoveSeries(long Series);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POINTSTYLECOLLECTION_H__12DF2525_6AF6_11D4_AC53_444553546170__INCLUDED_)
