#if !defined(AFX_POLAR_H__12DF253E_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_POLAR_H__12DF253E_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPolar wrapper class

class CPolar : public COleDispatchDriver
{
public:
	CPolar() {}		// Calls COleDispatchDriver default constructor
	CPolar(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPolar(const CPolar& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIsHalfRange();
	void SetIsHalfRange(BOOL);
	LPDISPATCH GetParent();
	BOOL GetAxisAllowNegative();
	void SetAxisAllowNegative(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POLAR_H__12DF253E_6AF6_11D4_AC53_444553546170__INCLUDED_)
