// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "polar.h"


/////////////////////////////////////////////////////////////////////////////
// CPolar properties

BOOL CPolar::GetIsHalfRange()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CPolar::SetIsHalfRange(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

LPDISPATCH CPolar::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x2, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CPolar::GetAxisAllowNegative()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CPolar::SetAxisAllowNegative(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CPolar operations
