//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VarroaPop.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_VARROAPOP_FORM              101
#define IDD_COLONY_DATA_FORM            102
#define ID_MOUSELABEL                   102
#define IDD_SIMULATION_FORM             103
#define IDD_ACTION_FORM                 107
#define IDR_MAINFRAME                   128
#define IDR_VARROATYPE                  129
#define IDD_CREATE_HEADER               134
#define IDD_SIMULATION_BAR              135
#define IDB_BITMAP1                     142
#define IDB_BITMAP2                     144
#define IDB_BITMAP3                     146
#define IDD_IMMIGRATION                 147
#define IDB_BITMAP4                     152
#define IDB_BITMAP5                     153
#define IDB_BITMAP6                     154
#define IDB_COS                         162
#define IDB_EXP                         163
#define IDB_LOG                         164
#define IDB_POLY                        165
#define IDB_SIN                         166
#define IDB_TAN                         167
#define IDD_GRAPHDIALOG                 168
#define IDD_SELECT_GRAPHS               170
#define IDD_PROGRESS                    173
#define IDB_BITMAP7                     180
#define IDD_SPLASH                      181
#define IDB_SPLASH                      184
#define IDD_OLECTRAGRAPHDLG             185
#define IDR_CHARTMENU                   187
#define IDB_BITMAP8                     196
#define IDI_SIN                         197
#define IDI_COS                         198
#define IDI_TAN                         199
#define IDI_POLY                        200
#define IDI_EXP                         201
#define IDI_LOG                         202
#define IDD_REMOVECOMB                  203
#define IDD_OPTIONS                     204
#define IDB_BITMAP10                    207
#define IDD_WEATHEREDIT                 208
#define IDR_MENUWEATHER                 210
#define IDB_BITMAP9                     218
#define IDB_WEATHERTOOLBAR              219
#define IDD_PROPPAGE_MEDIUM             225
#define IDD_WEATHER_FORM1               226
#define IDD_ACTION_FORM1                227
#define IDD_SPAN_VALUE                  228
#define IDD_ACTION_FORM2                229
#define IDD_PESTICIDE_PAGE              230
#define IDD_PESTICIDE_ADD               231
#define IDD_RESOURCE_PAGE               232
#define IDI_ICON1                       234
#define IDC_COLONY_GROUP                1000
#define IDC_EGGS_GROUP                  1002
#define IDC_WORKER_EGGS                 1003
#define IDC_DRONE_EGGS                  1004
#define IDC_WORKER                      1005
#define IDC_DRONE                       1006
#define IDC_NEW_COLONY_BUTTON           1007
#define IDC_LARVAE                      1008
#define IDC_WORKER_LARVAE               1009
#define IDC_DRONE_LARVAE                1010
#define IDC_ROW_HEADING1                1011
#define IDC_BROOD_WORKER_INFEST         1012
#define IDC_ROW_HEADING2                1013
#define IDC_LARVAE2                     1014
#define IDC_WORKER_BROOD                1015
#define IDC_DRONE_BROOD                 1016
#define IDC_ROW_HEADING3                1017
#define IDC_BROOD_DRONE_INFEST          1018
#define IDC_COLUMN_HEADING3             1019
#define IDC_WORKER2                     1020
#define IDC_DRONE2                      1021
#define IDC_LARVAE3                     1022
#define IDC_WORKER_ADULTS               1023
#define IDC_DRONE_ADULTS                1024
#define IDC_ROW_HEADING4                1025
#define IDC_ADULT_WORKER_INFEST         1026
#define IDC_ADULT_DRONE_INFEST          1027
#define IDC_ACCEPT_BUTTON               1028
#define IDC_COLONY_NAME_LIST            1031
#define IDC_COL_HIDE_BUTTON             1038
#define IDC_MITE_GROUP                  1039
#define IDC_WORKER_MITE_OFFSPRING       1041
#define IDC_MITE_ROW_HEADING            1042
#define IDC_DRONE_MITE_OFFSPRING        1043
#define IDC_MITE_SURVIVORSHIP_GROUP     1044
#define IDC_WORKER_MITE_SURVIVORSHIP    1045
#define IDC_DRONE_MITE_SURVIVORSHIP     1046
#define IDC_CANCEL_BUTTON_FOO           1060
#define IDC_WTH_HIDE_BUTTON             1061
#define IDC_SIM_HIDE_BUTTON             1062
#define IDC_SEL_HIDE_BUTTON             1063
#define IDC_DESELECT_COLONY             1068
#define IDC_COLONY_LIST                 1070
#define IDC_COLONIES_TO_SIMULATE        1074
#define IDC_COLONIES_AVAILABLE          1075
#define IDC_SAVE_COLONY_BUTTON          1076
#define IDC_CELSIUS_RADIO               1077
#define IDC_FAHRENHEIT_RADIO            1078
#define IDC_TEMP_FORMAT                 1079
#define IDC_WEATHER_CONTENTS            1081
#define IDC_W_BEG_TIME                  1083
#define IDC_W_END_TIME                  1084
#define IDC_W_BEG_DATE                  1085
#define IDC_W_END_DATE                  1086
#define IDC_RADIO_F                     1087
#define IDC_RADIO_C                     1088
#define IDC_SIM_TIME                    1091
#define IDC_SIM_DATE                    1092
#define IDC_AVTEMP                      1093
#define IDC_MAXTEMP                     1094
#define IDC_MINTEMP                     1095
#define IDC_RAINFALL                    1096
#define IDC_INTERVAL                    1097
#define IDC_WINDSPEED                   1098
#define IDC_RADIOMINMAX                 1099
#define IDC_RADIOHOURLY                 1100
#define IDC_SOLAR_RAD                   1101
#define IDC_BUTTON_GO                   1105
#define IDC_EDIT_SPERM                  1106
#define IDC_EDIT_F_AGE                  1107
#define IDC_EDIT_START                  1108
#define IDC_EDIT_STOP                   1109
#define IDC_SPIN_START                  1116
#define IDC_SPIN_STOP                   1117
#define IDC_SLIDERFORAGER               1118
#define IDC_EDITFORAGER                 1119
#define IDC_EDITQUEEN                   1120
#define IDC_FORAGERVAL                  1121
#define IDC_MAXEGGS                     1122
#define IDC_BUTTON_IM_SETUP             1123
#define IDC_RADIO_IM_ON                 1124
#define IDC_RADIO_IM_OFF                1125
#define IDC_GRAPH1                      1126
#define IDC_GRAPHPOLY                   1126
#define IDC_GRAPH2                      1127
#define IDC_GRAPHEXP                    1127
#define IDC_GRAPH3                      1128
#define IDC_GRAPHLOG                    1128
#define IDC_GRAPH4                      1129
#define IDC_IM_START                    1130
#define IDC_IM_END                      1131
#define IDC_IM_SELECTED                 1132
#define IDC_MITE_NUM                    1133
#define IDC_IM_TYPE                     1134
#define IDC_GRAPHSIN                    1134
#define IDC_GRAPHTAN                    1135
#define IDC_GRAPHCOS                    1136
#define IDC_CHECK_AW                    1140
#define IDC_CHECK_WB                    1141
#define IDC_CHECK_WL                    1142
#define IDC_CHECK_WE                    1143
#define IDC_CHECK_F                     1144
#define IDC_CHECK_IM                    1145
#define IDC_PROGRESS                    1146
#define IDC_CHECK_AD                    1150
#define IDC_CHECK_DB                    1151
#define IDC_CHECK_DL                    1152
#define IDC_CHECK_DE                    1153
#define IDC_CHECK_CS                    1154
#define IDC_CHECK_RM                    1155
#define IDC_CHECK_MWB                   1156
#define IDC_CHECK_MDB                   1157
#define IDC_CHECK_PWB                   1158
#define IDC_CHECK_PDB                   1159
#define IDC_CHECK_TM                    1160
#define IDC_SPLASH_CONT                 1161
#define IDC_CHECK_PRM                   1161
#define IDC_DISMISS                     1162
#define IDC_OLECTRACHART                1163
#define IDC_SLIDERQUEEN                 1165
#define IDC_QUEEN_DATE                  1168
#define IDC_EDIT_WKRDRN                 1169
#define IDC_EDIT_DELAY                  1170
#define IDC_RADIO_SCHED                 1171
#define IDC_RADIO_AUTO                  1172
#define IDC_ENABLE                      1173
#define IDC_STATICDATE                  1175
#define IDC_STATICAUTO                  1176
#define IDC_RQSLIDERQUEEN               1177
#define IDC_RADIO_RQ_ONCE               1179
#define IDC_RADIO_RQ_ANNUAL             1180
#define IDC_VT_ENABLE                   1181
#define IDC_TREATMENT_START             1182
#define IDC_TREATMENT_DURATION          1183
#define IDC_MORTALITY                   1184
#define IDC_TAB1                        1185
#define IDC_RESISTANT                   1185
#define IDC_MITE_PCT_RESISTANT          1186
#define IDC_ST_ENABLE                   1186
#define IDC_TREATMENT_START2            1187
#define IDC_VERSIONBOX                  1188
#define IDC_RADIOPOLY                   1189
#define IDC_RADIOEXP                    1190
#define IDC_REMCOMBEN                   1190
#define IDC_RADIOLOG                    1191
#define IDC_DATETIMEPICKER1             1191
#define IDC_RADIOSIN                    1192
#define IDC_PERCENT                     1192
#define IDC_DATETIMEEND                 1192
#define IDC_FOL_FORAGEEND               1192
#define IDC_RADIOCOS                    1193
#define IDC_SOIL_FORAGEBEGIN            1193
#define IDC_RADIOTAN                    1194
#define IDC_SOIL_FORAGEEND              1194
#define IDC_SD_FORAGEBEGIN              1195
#define IDC_RADIOWEEKLY                 1196
#define IDC_SD_FORAGEEND                1196
#define IDC_RADIODAILY                  1197
#define IDC_SUP_POL_BEGIN               1197
#define IDC_RADIOFIELDFIXED             1198
#define IDC_SUP_POL_END                 1198
#define IDC_RADIODIELDCOMMA             1199
#define IDC_SUP_NEC_BEGIN               1199
#define IDC_RADIOFIELDTAB               1200
#define IDC_SUP_NEC_END                 1200
#define IDC_CHECKCOLTITLES              1201
#define IDC_CHECKINITCONDS              1202
#define IDC_CHECKVERSION                1203
#define IDC_CHECKWTHCOL                 1204
#define IDC_WEATHERGRAPH                1205
#define IDC_CHECK_MD                    1206
#define IDC_CHECK_PMD                   1207
#define IDC_EDITINITSPORES              1208
#define IDC_EDITMORT10                  1209
#define IDC_EDITMORT25                  1210
#define IDC_EDITMORT50                  1211
#define IDC_EDITMORT75                  1212
#define IDC_EDIT6                       1213
#define IDC_EDITMORT90                  1213
#define IDC_BUTTON_ADD                  1214
#define IDC_EDIT9                       1214
#define IDC_LIST1                       1215
#define IDC_LIST_TREAT_DATES            1215
#define IDC_EDIT10                      1215
#define IDC_LIST_EVENT_LOG              1215
#define IDC_BUTTON_DEL                  1216
#define IDC_EDIT11                      1216
#define IDC_EDIT12                      1217
#define IDC_STATIC_WEATHERFILE          1218
#define IDC_BUTTON1                     1219
#define IDC_BUTTON_SEL_WEATHER          1219
#define IDC_BUTTON_EGG_SPAN             1219
#define IDC_BUTTON_LARVAE_SPAN          1220
#define IDC_STATIC_WF_NAME              1221
#define IDC_BUTTON_BROOD_SPAN           1221
#define IDC_BUTTON_ADULT_SPAN           1222
#define IDC_BUTTON_FORAGER_SPAN2        1223
#define IDC_BUTTON_ADULT_SPAN2          1224
#define IDC_CUSTOM4                     1225
#define IDC_GRIDCTRL1                   1226
#define IDC_DRV_Ctrl2                   1231
#define IDC_EDIT_VAL                    1232
#define IDC_VAL_LABEL                   1233
#define IDC_DATETIMESTART               1234
#define IDC_BUTTON_DEL_ITEM             1235
#define IDC_CHECK_EN_EGG                1236
#define IDC_CHECK_EN_LARV               1237
#define IDC_BUTTON2                     1237
#define IDC_CHECK_EN_BROOD              1238
#define IDC_CHECK_EN_EGG4               1239
#define IDC_CHECK_EN_ADULT              1239
#define IDC_CHECK1                      1239
#define IDC_CHECK_EN_ADULT2             1240
#define IDC_CHECK_EN_FORAGER            1240
#define IDC_IED_EXPOSURE_DATE           1240
#define IDC_CHECK2                      1240
#define IDC_CHECK3                      1241
#define IDC_CHECK_EN_ADULT3             1241
#define IDC_CHECK_EN_ADULTSP            1241
#define IDC_EDIT_IED_M_EGG              1242
#define IDC_CHECK4                      1242
#define IDC_CHECK_DFG                   1242
#define IDC_CHECK_NPCont                1242
#define IDC_EDIT_IED_M_LARVAE           1243
#define IDC_CHECK_DWA                   1243
#define IDC_EDIT_IED_M_ADULT            1244
#define IDC_EDIT_IED_M_PUPAE            1245
#define IDC_EDIT_IED_M_FORAGERS         1246
#define IDC_SLIDER_MORT_EGG             1247
#define IDC_PESTICIDE_AD_SLOPE          1249
#define IDC_PESTICIDE_C_P1              1250
#define IDC_PESTICIDE_AC_SLOPE2         1250
#define IDC_PESTICIDE_LARV_SLOPE        1251
#define IDC_PESTICIDE_LV_LD             1252
#define IDC_PESTICIDE_AC_SLOPE          1252
#define IDC_PESTICIDE_KOW               1253
#define IDC_PESTICIDE_KOC               1254
#define IDC_PESTICIDE_C_N4              1255
#define IDC_PESTICIDE_HL                1255
#define IDC_PESTICIDE_NAME              1256
#define IDC_PESTICIDE_KOC3              1256
#define IDC_PESTICIDE_CF                1256
#define IDC_PESTICIDE_C_P2              1257
#define IDC_PESTICIDE_C_P3              1258
#define IDC_PESTICIDE_C_P4              1259
#define IDC_PESTICIDE_C_P5              1260
#define IDC_PESTICIDE_C_P6              1261
#define IDC_PESTICIDE_C_P7              1262
#define IDC_PESTICIDE_C_P8              1263
#define IDC_PESTICIDE_C_N1              1264
#define IDC_PESTICIDE_C_N2              1265
#define IDC_PESTICIDE_C_N3              1266
#define IDC_PESTICIDE_C_N5              1267
#define IDC_PESTICIDE_C_N8              1268
#define IDC_PESTICIDE_C_N6              1269
#define IDC_PESTICIDE_C_N7              1270
#define IDC_PESTICIDE_AD_SLOPE7         1271
#define IDC_PESTICIDE_HALFLIFE          1271
#define IDC_EDIT1                       1272
#define IDC_EDIT2                       1273
#define IDC_PESTICIDE_AD_SLOPE8         1273
#define IDC_PESTICIDE_AC_LD50_2         1273
#define IDC_EDIT3                       1274
#define IDC_EDIT4                       1275
#define IDC_EDIT5                       1276
#define IDC_PESTICIDE_CONFACT           1276
#define IDC_EDIT7                       1277
#define IDC_PESTICIDE_AD_LD50           1278
#define IDC_PESTICIDE_LARV_LD50         1279
#define IDC_FOLIAR_APP_DATE             1280
#define IDC_FOL_FORAGEBEGIN             1281
#define IDC_PESTICIDE_AC_LD50           1282
#define IDC_EDIT8                       1283
#define IDC_CHECK_NS                    1283
#define IDC_CHECK_PS                    1284
#define IDC_CHECK_NCONC                 1285
#define IDC_CHECK_PCONC                 1286
#define IDC_BUTTON3                     1287
#define IDC_CHECK_DDL                   1288
#define IDC_CHECK_DWL                   1289
#define IDC_CHECK_DDA                   1290
#define IDC_RADIO_MANUAL                1292
#define IDC_EDIT_MAX                    1293
#define IDC_EDIT_MIN                    1294
#define IDC_STATICMAX                   1295
#define IDC_STATICMIN                   1296
#define IDC_BUTTON4                     1297
#define IDC_BUTTON_SELCONTFILE          1297
#define IDC_STATIC_CONTFILENAME         1298
#define IDC_CHECK_SUP_POP_EN            1299
#define IDC_CHECK_SUP_NEC_EN            1300
#define IDC_EDIT_SUP_POL_AMT            1301
#define IDC_EDIT_SUP_NEC_AMT            1302
#define IDC_SCROLLBAR1                  1302
#define IDC_EDIT1_INIT_POLLEN           1303
#define IDC_EDIT_INIT_POLLEN            1303
#define IDC_EDIT_INIT_NECTAR            1304
#define IDC_RADIO1                      1305
#define IDC_RADIO2                      1306
#define IDC_BUTTON_UPDATE_POL           1307
#define IDC_CUSTOM1                     1308
#define IDC_EDIT_MAXPFORAGERS           1309
#define IDC_CHECK5                      1310
#define IDC_CHECK_RESOURCES             1310
#define IDC_CHECK_POL_ANN               1311
#define IDC_CHECK_NEC_POL               1312
#define IDC_CHECK_NEC_AN                1312
#define IDC_EDIT_MAX_POLLEN             1314
#define IDC_EDIT_INIT_NECTAR2           1315
#define IDC_EDIT_MAX_NECTAR             1315
#define ID_CREATE_PROPSHEET             32771
#define ID_SHOW_PROPSHEET               32772
#define ID_VIEW_PARAMETERS              32773
#define ID_FILE_NEW_NEWSESSION          32774
#define ID_FILE_NEW_NEWCOLONY           32775
#define ID_SELECT_GRAPH                 32777
#define ID_VIEW_PLOTDATA                32778
#define ID_FILE_SAVE_SESSION            32779
#define ID_FILE_SAVE_RESULTS            32781
#define IDR_PRINTER                     32783
#define IDR_FILE                        32784
#define ID_VIEW_COMBREMOVALDATE         32785
#define ID_VIEW_DATA_FREQ               32786
#define ID_VIEW_OPTIONS                 32787
#define ID_WEATHER_CREATENEWWEATHERFILE 32788
#define ID_WEATHER_EDITCURRENTWEATHERFILE 32789
#define ID_WEATHER_EDITWEATHERFILEFROMDISK 32790
#define ID_WEATHER_FILE_SAVEAS          32793
#define ID_WEATHER_FILE_EXIT            32794
#define ID_VIEW_ZOOMIN                  32795
#define ID_VIEW_ZOOMOUT                 32796
#define ID_WEATHER_FILE_OPEN            32797
#define ID_WEATHER_FILE_SAVE            32798
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32806                  32806
#define ID_HELP_REPORTAPROBLEM          32807
#define ID_BUTTON32810                  32810
#define ID_BUTTON_COLEXPAND             32810
#define ID_BUTTON32811                  32811
#define ID_BUTTON_COLREDUCE             32811
#define ID_VIEW_SHOWWARNINGS            32812
#define ID_INDICATOR_WEATHER            59141
#define IDS_VPVERSION                   59142
#define ID_INDICATOR_RES_FREQ           59143
#define ID_INDICATOR_SESSION            59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1312
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
