// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "symbolstyle.h"


/////////////////////////////////////////////////////////////////////////////
// CSymbolStyle properties

long CSymbolStyle::GetShape()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CSymbolStyle::SetShape(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

unsigned long CSymbolStyle::GetColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CSymbolStyle::SetColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CSymbolStyle::GetSize()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CSymbolStyle::SetSize(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

LPDISPATCH CSymbolStyle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CSymbolStyle::GetIsDefault()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CSymbolStyle::SetIsDefault(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSymbolStyle operations
