// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "title.h"

// Dispatch interfaces referenced by this interface
#include "border.h"
#include "label.h"
#include "interior.h"
#include "location.h"
#include "font.h"


/////////////////////////////////////////////////////////////////////////////
// CTitle properties

CBorder CTitle::GetBorder()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return CBorder(pDispatch);
}

long CTitle::GetAdjust()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CTitle::SetAdjust(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CLabel CTitle::GetText()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CLabel(pDispatch);
}

CInterior CTitle::GetInterior()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return CInterior(pDispatch);
}

CLocation CTitle::GetLocation()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CLocation(pDispatch);
}

BOOL CTitle::GetIsShowing()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CTitle::SetIsShowing(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

LPDISPATCH CTitle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x7, VT_DISPATCH, (void*)&result);
	return result;
}

COleFont CTitle::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x8, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CTitle::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x8, VT_DISPATCH, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTitle operations
