#if !defined(AFX_TITLE_H__12DF255D_6AF6_11D4_AC53_444553546170__INCLUDED_)
#define AFX_TITLE_H__12DF255D_6AF6_11D4_AC53_444553546170__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder;
class CLabel;
class CInterior;
class CLocation;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CTitle wrapper class

class CTitle : public COleDispatchDriver
{
public:
	CTitle() {}		// Calls COleDispatchDriver default constructor
	CTitle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTitle(const CTitle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CBorder GetBorder();
	long GetAdjust();
	void SetAdjust(long);
	CLabel GetText();
	CInterior GetInterior();
	CLocation GetLocation();
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	LPDISPATCH GetParent();
	COleFont GetFont();
	void SetFont(LPDISPATCH);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TITLE_H__12DF255D_6AF6_11D4_AC53_444553546170__INCLUDED_)
