// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "valuelabel.h"

// Dispatch interfaces referenced by this interface
#include "Label.h"


/////////////////////////////////////////////////////////////////////////////
// CValueLabel properties

double CValueLabel::GetValue()
{
	double result;
	GetProperty(0x1, VT_R8, (void*)&result);
	return result;
}

void CValueLabel::SetValue(double propVal)
{
	SetProperty(0x1, VT_R8, propVal);
}

CLabel CValueLabel::GetLabel()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CLabel(pDispatch);
}

LPDISPATCH CValueLabel::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CValueLabel operations
