// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcTextLayout;

/////////////////////////////////////////////////////////////////////////////
// CVcAxisTitle wrapper class

class CVcAxisTitle : public COleDispatchDriver
{
public:
	CVcAxisTitle() {}		// Calls COleDispatchDriver default constructor
	CVcAxisTitle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcAxisTitle(const CVcAxisTitle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	LPDISPATCH GetBackdrop();
	LPDISPATCH GetVtFont();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CVcTextLayout GetTextLayout();
	short GetTextLength();
	void SetRefFont(LPDISPATCH newValue);
	LPDISPATCH GetFont();
};
