// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcTextLayout wrapper class

class CVcTextLayout : public COleDispatchDriver
{
public:
	CVcTextLayout() {}		// Calls COleDispatchDriver default constructor
	CVcTextLayout(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcTextLayout(const CVcTextLayout& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetHorzAlignment();
	void SetHorzAlignment(long nNewValue);
	long GetVertAlignment();
	void SetVertAlignment(long nNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	BOOL GetWordWrap();
	void SetWordWrap(BOOL bNewValue);
};
