// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "view3d.h"


/////////////////////////////////////////////////////////////////////////////
// CView3D properties

long CView3D::GetDepth()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CView3D::SetDepth(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CView3D::GetElevation()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CView3D::SetElevation(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CView3D::GetRotation()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CView3D::SetRotation(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

LPDISPATCH CView3D::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

short CView3D::GetShading()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CView3D::SetShading(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CView3D operations
